apiVersion: v1
kind: ServiceAccount
metadata:
  name: airtable-sync-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airtable-sync-controller
rules:
  - apiGroups: ["apps", ""]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airtable-sync-controller
subjects:
  - kind: ServiceAccount
    name: airtable-sync-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: airtable-sync-controller
  apiGroup: rbac.authorization.k8s.io
