apiVersion: v1
kind: Secret
metadata:
  name: airtable-credentials
  namespace: default
type: Opaque
stringData:
  api-key: patx9H8Z5CpvEQCZ1.5b02ca1438712d21ac7809e82b6bead7bc2512e54ce0676b6bde72e09eb8e7bf