apiVersion: v1
kind: ConfigMap
metadata:
  name: airtable-config
  namespace: default
data:
  base-id: appiaCnT5CjmEukDq
  table-name: tblmuTTidcm3zJDSL
  view-name: Stage 4 - AI Chatting
  cupid-token: 5cb75ec7721e3ed209fa22fc55480edf
  hotbot-token: 128171b0-b4b9-49a1-bd28-04537666847d7330
  dpa-platform-api-key: HC18ytNrQXnsI1X33UfgxMmZq2SWwvy5MTBtsZrAUck